version: '3'
services:
  app:
    image: golang:1.15-buster
    volumes:
    - .:/app
    working_dir: /app
    command: ./build
    ports:
    - "8181:8181"
    environment:
    - PORT=8181
    - GITHUB_SECRET
